i\"
.\" Man page for gpt-wizard command, by Keith Thompson, kst@sdsc.edu
.\"
.\" $Id: gpt-wizard.1,v 1.36 2004-02-17 05:00:41-08 kst Exp $
.\" $Source: /home/kst/CVS_smov/tools/gpt-wizard/gpt-wizard.1,v $
.\"
.\" @Copyright@
.\" 
.\" Copyright (c) 2004 The Regents of the University of California. All
.\" rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are
.\" met:
.\" 
.\" 1. Redistributions of source code must retain the above copyright
.\" notice, this list of conditions and the following disclaimer.
.\" 
.\" 2. Redistributions in binary form must reproduce the above copyright
.\" notice, this list of conditions and the following disclaimer in the
.\" documentation and/or other materials provided with the distribution.
.\" 
.\" 3. All advertising materials mentioning features or use of this
.\" software must display the following acknowledgement: This product
.\" includes software developed by the Grid and Cluster Computing Group
.\" at the San Diego Supercomputer Center and its contributors.
.\" 
.\" 4. Neither the name of the Center nor the names of its contributors
.\" may be used to endorse or promote products derived from this software
.\" without specific prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS''
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
.\" THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\" WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
.\" OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
.\" IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\" 
.\" @Copyright@
.\" 
.TH GPT\-WIZARD 1 2004-02-12 SDSC
.SH NAME
gpt\-wizard \- Build and install GPT bundles and packages
.SH SYNOPSIS
.B "gpt\-wizard \-help"
.br
.B "gpt\-wizard [options] config\-file"

.SH VERSION
.\"
.\" The layout of the following line is significant; see make\-release.
.\"
This documentation is for release 0.6.1 of
.IR gpt\-wizard .

.SH DESCRIPTION
The
.I gpt\-wizard
command builds and installs a specified set of GPT bundles and
packages, driven by a simple ASCII configuration file.  (GPT is the
.IR "Grid Packaging Toolkit" .)
The intent is to automate as much as possible of the process of
installing Globus and other software components, and starting up the
services they provide.

Note that some things are difficult or impractical to automate.
(For example,
.I gpt\-wizard
doesn't attempt to automatically update the /etc/inetd.conf file;
there are too many local conventions to worry about, and many sites
manage it in such a way that any changes would be clobbered.)  The
.I gpt\-wizard
command keeps track of these manual steps and prints a summary.
This summary is printed in a single well\-marked block at the end of
the output.

If the
.I gpt\-wizard
command is executed from the root account, most of the installation
steps will actually be performed by a non\-root account such as
"globus" (see the INSTALLER_USER configuration variable).  If it's
executed from a non\-root account, all installation steps will of
course be performed by that account; any steps that require root access
will be included in the summary of manual steps to be performed later.

The
.I gpt\-wizard
command creates a directory called
.I .gpt\-wizard
under the
.I $GLOBUS_LOCATION
directory.  This directory will contain a copy of the configuration
file and a plain text file called
.IR info ,
which contains summary information about the build, including any
manual steps to be executed.

I highly recommend capturing the output of each
.I gpt\-wizard
run in a log file for later perusal.

The web page for the
.I gpt\-wizard
command is
.br
.IR <http://www.sdsc.edu/~kst/gpt\-wizard/> .
.br
The
.I gpt\-wizard
command should be available at
.br
.IR <ftp://ftp.sdsc.edu/pub/sdsc/globus/software/gpt\-wizard/> ;
.br
each version is in the file
.I gpt\-wizard\-VERSION.tar.gz
in that directory.

.SH BACKGROUND
This command is a Perl script which incorporates much of the
experience I've acquired in doing multiple installations of Globus
and NMI software.  Rather than keeping track of the various steps and
system\-specific exceptions in an error\-prone checklist, I decided to
write this Perl script to do as much of the work as possible for me
(lazy bum that I am).

.I gpt\-wizard 
is not a "wizard" in the sense used in Microsoft Windows, i.e.,
an interactive program that leads the user through a configuration
process step by step.  It is a batch mode configuration and build program; 
.I gpt\-wizard
was just the cool name I came up with.  (Some early unreleased versions
were called
.IR install\-nmi .)

.SH OPTIONS
.I gpt\-wizard
uses Perl's
.I Getop::Long
module to parse its command\-line arguments.
.br
Options may be prefixed with either "\-" or "\-\-".
.br
Option names may be abbreviated uniquely.

.IP \-help
Display a brief help message on stdout and exit.

.IP \-version
Display version information and exit.

.IP \-validate\-only
Validate the configuration file, display some information, and exit without
building anything.  Useful to detect errors in a configuration file.

.IP \-cleanup
Delete the temporary working directory on completion.
This is the default behavior.  Use "\-nocleanup" to keep the
temporary working directory.  (Its name will be something like
.I /tmp/gpt\-wizard\-1043365463\-17640
or
.IR TEMP_DIR/gpt\-wizard\-1043365463\-17640 ;
see
.BR "CONFIGURATION OPTIONS" ,
below.

.IP \-postinstall
Run the
.I gpt\-postinstall
command.  This is the default behavior; use "\-nopostinstall" if
you don't want to run
.IR gpt\-postinstall .

.IP \-startup
Update system files and start services.  This is allowed only when
.I gpt\-wizard
is run as root.  The default is "\-nostartup".  (In some early releases,
"\-startup" was the default.)
.br
.B NOTE:
This is currently supported only on Linux systems.

.IP \-gpt\-verbose
Pass the "\-verbose" option to
.I gpt\-install
and/or
.IR gpt\-build .
This will produce voluminous output, especially when building source
bundles and packages.

.IP \-gpt\-install\-only
Pass the "\-install\-only" option to
.IR gpt\-build .
This doesn't affect binary installations
.RI ( gpt\-install ).
.B NOTE:
This option is probably obsolete for the current version of
.IR GPT .

.IP \-gpt\-ignore\-errors
Ignore errors from
.I gpt\-install
and
.IR gpt\-build .
Not recommended.

.IP \-aix\-kludge
Use an existing GPT installation.  This was implemented to work around
some obscure problems on an AIX system.  Not recommended unless you know
what you're doing.

.IP \-debugging
Enable debugging output.

.SH CONFIGURATION FILE
The
.I gpt\-wizard
command requires a configuration file to be specified on the
command line.  The name of the file is irrelevant.  I typically use
something like
.br
.B "	<machine\-name>\-globus\-<version>\-<kind>.conf"
.br
for example,
.br
.B "	tf005i\-globus\-2.2.3\-src.conf"
.br
but if you want to call it
.B foobar.baz
I won't complain.

The configuration file is a plain text file with a simple syntax.
A
.B '\\\\'
character at the end of a line (possibly followed by whitespace) indicates
a line continuation.  Everything from a
.B '#'
character to the end of the line is treated as a comment and ignored.
(This means that a variable value cannot include a
.B '#'
character; there is no mechanism for specifying a literal
.BR '#' .)
Leading whitespace, trailing whitespace, and empty lines are also
ignored.  The effect of combining
.B '\\\\'
and
.B '#'
characters on the same physical line is undefined; don't try it.

Each line consists of a variable name, followed by whitespace, followed
by the value of the variable.  All variable names must be specified
in upper case.  The value is generally an arbitrary string, which
may include embedded blanks.  There may be restrictions depending on
the type of the variable (see below).  String values are not enclosed
in quotation marks; any quotation marks are simply taken as part of
the value.  For Boolean variables a false value  may be specified
as "0", "no", or "false", and a true value may be specified as "1",
"yes", or "true" (without the quotation marks, of course); the value
is case\-insensitive.  Some variables are optional, some are mandatory,
and some may appear multiple times.  Certain variables may also
have attributes associated with them; these are given in the form
"name=value" on the same line.

If a value starts with
.IR ~user , 
and
.I user
has an account on the system,
.IR ~user
is replaced with
.IR user 's
home directory.  If there is no such user, no substitution is done
(which will probably cause an error).  (Replacement of
.I ~
by the value of $HOME is not supported.)

Previous versions of
.IR gpt\-wizard ,
up to release 0.4, supported specification of URLs (starting with either
"ftp://" or "http://") for some files.  This is no longer supported;
all files must be directly visible.  (This feature wasn't being used, and I'm
not certain that it worked properly.)  The DOWNLOAD_DIR and WGET
configuration variables are no longer supported.

.SH CONFIGURATION OPTIONS

.IP .PREFIX
This is a pseudo\-option.  It specified a default prefix to be prepended,
with a
.B '/'
character, to any following file name given as a relative path name.
It can be used to avoid extremely long lines in configuration files.

.IP CONFIG_FILE_REVISION
Typically an RCS or CVS "Revision" tag, but it can be any arbitrary string.
.br
Example:
.br
.B "	CONFIG_FILE_REVISION $Revision: 1.36 $"
.br
Type: string
.br
Optional.

.IP TEMP_DIR
Location for
.IR gpt\-wizard 's
temporary working directory.  The temporary directory will be created
under the specified directory.
.br
Type: existing directory
.br
Optional.  Default is "/tmp".  This must be specified as an absolute
pathname.

.IP TAR
The full path name of the
.I tar
command.
.br
Type: executable file
.br
Optional.  This is only necessary if the
.I tar
command does not appear in the
.B PATH
specified in the configuration file.

.IP GZIP
The full path name of the
.I gzip
command.
.br
Type: executable file
.br
Optional.  This is only necessary if the
.I gzip
command does not appear in the
.B PATH
specified in the configuration file.

.IP PATH
The value for the
.B $PATH
environment variable.
.br
Mandatory.

.IP ENV
An environment variable setting, of the form "VAR" or "VAR=value".
If no value is specified, the variable is set to the empty string.
.br
Type: string
.br
Optional.  May occur multiple times.

.IP INSTALLER_USER
The name of the Unix account to use for the installation.
.br
Type: string (must be a valid user name)
.br
Optional.  Default is "globus" if running as root, the current user
otherwise.  If you run
.I gpt\-wizard
from a non-root account, you may not specify an INSTALLER_USER other
than your current account; in this case, it may be best not to specify
an INSTALLER_USER at all.

.IP INSTALLER_GROUP
The name of the Unix group to use for the installation.
.br
Type: string (must be a valid group name)
.br
Optional.  Default is "globus" if running as root, the current primary
group otherwise.  If you run
.I gpt\-wizard
from a non-root account, you may not specify an INSTALLER_GROUP
other than your current primary group, even if you are a member of
the specified group; in this case, it may be best not to specify an
INSTALLER_GROUP at all.

.IP USE_SDSC_SU
Use the non\-standard "su" command in use at SDSC.  Probably not useful
for sites other than SDSC.
.br
Type: boolean
.br
Optional.  Default is 0.

.IP UMASK
Specify an octal umask for the installation.  The default value is almost
always best.
.br
Type: string (must be a valid octal number)
.br
Optional.  Default is 022.

.IP GPT_TARBALL
The location of the source tarball
.RI ( *.tar.gz )
file for GPT.  Binary and RPM distributions of GPT are not yet supported
though binary and RPM GPT bundles are supported).
.br
As of
.I gpt\-wizard
release 0.5, GPT 1.X is no longer supported; all current Globus releases
include GPT 2.X or better.
.br
Type: file name
.br
Mandatory.

.IP BUNDLE
A GPT bundle or package.  It may be a source, binary, or rpm bundle.
(In a future release,
.I gpt\-wizard
may require a separate PACKAGE option for packages.)  Multiple
bundles may be (and typically are) specified in a single config file.
If necessary, the same bundle may be specified multiple times with
different attributes, for example if it's necessary to build a bundle
with "\-static" for some flavors and without "\-static" for others.
.br
Attributes:
.br
        kind=binary
.I or
kind=source
.I or
kind=rpm
.br
        flavor=<flavor>
.br
        option=<option>
.br
If a kind is not specified,
.I gpt\-wizard
attempts to guess based on the file name.
.br
Multiple flavors may be specified, separated by commas, e.g.,
"flavor=gcc32dbg,gcc32".
.br
Options are passed to gpt\-install or gpt\-build, after expanding
commas to blanks.
.br
Type: file name
.br
Mandatory.  Multiple bundles may be specified.

.IP UPDATE
A GPT update package.  This is normally a source package.
.br
The same attributes may be specified as for bundles.
.br
Type: file name
.br
Optional.  Multiple update packages may be specified.

.IP PRE_POSTINSTALL
An ugly kludge to specify a command to be executed before running
gpt\-postinstall.  So far, I have only used this on AIX to run
mds\-aix\-relink.sh, which works around some AIX\-specific libtool
problems.  Any occurrence of the string "BUILD_DIR" is replaced with
the name of the temporary build directory.
.br
Not recommended unless you know what you're doing.
.br
Type: string (must be a valid command).
.br
Optional.

.IP GPT_LOCATION
The location in which to install GPT, the Grid Packaging Toolkit.
If this is not specified, use the same directory as
.BR GLOBUS_LOCATION .
.br
Type: new directory (must be empty if it already exists).
.br
Optional.

.IP GLOBUS_LOCATION
The location in which to install the Globus toolkit and other components.
.br
Type: new directory (must be empty if it already exists).
.br
Mandatory.

.IP GLOBUS_LOCAL_DIRECTORY
A local directory in which to install the "var" and "tmp" directories and
certain files under the "etc" directory.  If
.B GLOBUS_LOCATION
is on an NFS\-mounted file system, the gatekeeper
(which runs as root) will often not be able to write to its log file,
.IR $GLOBUS_LOCATION/var/globus\-gatekeeper.log .
Also, some files need to be unique for each system on which
Globus services are running.  See Globus Bugzilla #660,
.IR <http://bugzilla.globus.org/bugzilla/show_bug.cgi?id=660> .
If
.B GLOBUS_LOCAL_DIRECTORY
is specified (normally on a local filesystem), certain subdirectories
and files will be created as symbolic links into the specified
directory.
.br
Type: new directory (must be empty if it already exists).
.br
Optional.
.br
Note: This replaces and generalizes the GLOBUS_VAR_DIRECTORY
configuration variable from earlier versions of
.IR gpt\-wizard .

.IP GLOBUS_HOSTNAME
Set the environment variable
.I $GLOBUS_HOSTNAME
to the specified value.
If the system host name (the value printed by the
.BR hostname (1)
command) doesn't match the primary name by which the system is known on
the network (via a reverse DNS lookup),
.B GLOBUS_HOSTNAME
should be set
to the network name.
.br
This option is equivalent to
.br
.B "ENV GLOBUS_HOSTNAME=..."
.br
Type: string
.br
Optional.

.IP GRID_MAPFILE
The name of a file to be copied to
.I /etc/grid\-security/grid\-mapfile
if the "-startup" option is specified.
This is a text file mapping Globus certificate subject names to Unix
account names.  See the Globus documentation for more information.
.br
Type: file name
.br
Optional.

.IP HOST_CERT
The name of a file containing the Globus host certificate,
also known as the gatekeeper certificate.  It will be copied to
.I /etc/grid\-security/hostcert.pem
if the "-startup" option is specified.
.br
Type: file name
.br
Optional.

.IP HOST_KEY
The name of a file containing the Globus host private key, also known as
the gatekeeper key.  It will be copied to
.I /etc/grid\-security/hostkey.pem
if the "-startup" option is specified.
.br
Type: file name
.br
Optional.

.IP LDAP_CERT
The name of a file containing the Globus LDAP certificate, to be used
for non\-anonymous MDS queries (see the
.I grid\-info\-search
command).  It will be copied to
.I /etc/grid\-security/ldap/ldapcert.pem
if the "-startup" option is specified.
.br
Type: file name
.br
Optional.

.IP LDAP_KEY
The name of a file containing the Globus LDAP private key, to be used
for non\-anonymous MDS queries (see the
.I grid\-info\-search
command).  It will be copied to
.I /etc/grid\-security/ldap/ldapkey.pem
if the "-startup" option is specified.
.br
Type: file name
.br
Optional.

.IP BATCH_SYSTEM
For Globus 2.X releases prior to 2.2, this specifies a batch system
to be used.  Allowed values are
.IR condor ,
.IR easymcs ,
.IR fork ,
.IR glunix ,
.IR grd ,
.IR loadleveler ,
.IR lsf ,
.IR nqe ,
.IR nswc ,
.IR pbs , 
.IR pexec ,
and
.IR prun . 
Starting with Globus 2.2, batch systems are configured by installing an
additional package, making this option obsolete.
.br
Type: string
.br
Optional.

.IP JOB_MANAGER
For Globus 2.X releases starting with 2.2, specify a job manager.
The first argument is the name of the batch system; other arguments
are passed to the setup script.
.br
This option is newly implemented; use with caution.
.br
Example:
.br
.B "	JOB_MANAGER pbs \-cpu\-per\-node 2 \-remote\-shell ssh"
.br
Type: job_manager
\.br
Optional.

.IP CA_CERT_TARBALL
The name of a tarball file
.RI ( *.tar.gz )
containing certificates
and signing policies for one or more certificate authorities.
The certificate
.RI ( *.0 )
and policy
.RI ( *.signing_policy )
files should be at the top level of the tarball.  By default, only the
Globus CA is recognized; since the Globus CA has expired, it will be
necessary to install one or more others.  One possible value is a local
copy of
.I "ftp://ftp.sdsc.edu/pub/sdsc/globus/CA/certificates.tar.gz"
(but be sure to read the enclosed
.I README
file before deciding to use it).
.br
Type: file name
.br
Optional.

.SH SECURITY
Much of the Globus Toolkit is concerned with security.  This doesn't
necessarily mean that using Globus makes your system secure; in fact,
there are a number of things you can do wrong that can make your
system or your account less secure.

Globus certificates, such as hostcert.pem, ldapcert.pem, and
usercert.pem, may be made publicly visible without any danger.
The corresponding private key files, however, must be kept secret.
If any of these files are revealed, a malicious user could possibly
masquerade as your system or as you.

The file
.I /etc/grid\-security/grid\-mapfile
specifies the mapping of Globus subject names to user names.  This file
can be publicly visible, but must be modifiable
.B only
by trusted users.

This section does not purport to be a complete summary of Globus
security issues.  It may not even be entirely correct.

The
.I gpt\-wizard
command attempts to install files with the correct ownership and
permissions, but does not otherwise deal directly with security issues.
If you think you've found a security\-related problem in
.IR gpt\-wizard ,
please let me know as soon as possible by e\-mail to
.BR kst@sdsc.edu .

.SH REFERENCES
.IP GPT
GPT is the Grid Packaging Toolkit, developed at NCSA.  It is the
method used to install Globus for releases 2.0 and later.  A version
is provided with the Globus Toolkit; see also
.IR <http://www.gridpackagingtools.org/> .

.IP "Globus Project"
The Globus Project develops the Globus Toolkit.  If you've read this far,
you probably already know what that is.
.br
See
.IR <http://www.globus.org> .

.IP NMI
NMI, or NSF Middleware Infrastructure, is a project sponsored by the
National Science Foundation.  The project packages and distributes Globus
and other grid\-related software components.
.br
See
.IR <http://www.nsf\-middleware.org> .

.IP SDSC
The San Diego Supercomputer Center,
.IR <http://www.sdsc.edu> .
The author of
.I gpt\-wizard
works there.  Hi.

.IP NCSA
The National Center for Supercomputing Applications,
.IR <http://www.ncsa.uiuc.edu> .
GPT, the Grid Packaging Toolkit, was developed there.

.SH EXIT STATUS
The
.I gpt\-wizard
command returns an exit status of zero if it succeeds, non\-zero if
it fails.

.SH BUGS
The "TO DO" section in the
.I gpt\-wizard
script itself includes a number of ideas for features that I intend
to implement.  There are undoubtedly many other good ideas that I
haven't thought of yet, and bugs that I haven't yet found.

This documentation would probably benefit from some outside review.
If anything here is unclear, it's probably the author's fault, not
the reader's fault.

Please send any bug reports or suggestions to the author by e\-mail.

.SH AUTHOR
Keith Thompson, San Diego Supercomputer Center, kst@sdsc.edu
