#!/bin/sh

BUILD_DIR=${HOME}/build/side_tools/BUILD

cd ${BUILD_DIR}/globus_mds_back_giis-0.5
ld -o libback_giis.so.0 ../globus_openssl_module-0.1/library/*.o ../globus_gsi_openssl_error-0.2/library/*.o ../globus_gsi_proxy_ssl-0.1/library/*.o ../globus_gsi_sysconfig-0.1/library/*.o ../globus_common-3.4/library/*.o ../globus_gss_assist-3.1/*.o *.o ../globus_gsi_credential-0.3/library/*.o ../globus_gssapi_gsi-3.2/library/*.o ../globus_gsi_proxy_core-0.3/library/*.o -bnoentry -G -bexpall -bM:SRE -lc -ldl
cp libback_giis.so.0 $GLOBUS_LOCATION/libexec/openldap/vendorcc32dbgpthr
cd ${BUILD_DIR}/globus_ldapmodules-0.5
ld -o libback_ldif.so.0 ../globus_gss_assist-3.1/*.o *.o ../globus_gsi_callback-0.2/library/oldgaa/*.o ../globus_gsi_proxy_core-0.3/library/*.o ../globus_gsi_callback-0.2/library/*.o ../globus_gsi_cert_utils-0.2/library/*.o ../globus_gssapi_gsi-3.2/library/*.o -bnoentry -G -bexpall -bM:SRE -lc -ldl
cp libback_ldif.so.0 $GLOBUS_LOCATION/libexec/openldap/vendorcc32dbgpthr

cd $GLOBUS_LOCATION/libexec/openldap/vendorcc32dbgpthr
ln -sf  libback_giis.so.0 libback_giis.so
ln -sf  libback_ldif.so.0 libback_ldif.so

cat > $GLOBUS_LOCATION/libexec/openldap/vendorcc32dbgpthr/libback_giis.la << EOF


# libback_giis.la - a libtool library file
# Generated by ltmain.sh - GNU libtool 1.3.5 (1.385.2.206 2000/05/27 11:12:27)
#
# Please DO NOT delete this file!
# It is necessary for linking the library.

# The name that we can dlopen(3).
dlname='libback_giis.so.0'

# Names of this library.
library_names=''

# The name of the static archive.
old_library=''

# Libraries that this one depends upon.
dependency_libs=' -L$GLOBUS_LOCATION/lib -lglobus_common_vendorcc32dbgpthr -lglobus_gss_assist_vendorcc32dbgpthr -lldap_vendorcc32dbgpthr -llber_vendorcc32dbgpthr -lglobus_gssapi_gsi_vendorcc32dbgpthr -lsasl_vendorcc32dbgpthr -lglobus_ssl_utils_vendorcc32dbgpthr -lltdl_vendorcc32dbgpthr -lssl_vendorcc32dbgpthr -lcrypto_vendorcc32dbgpthr'

# Version information for libback_giis.
current=0
age=0
revision=0

# Is this an already installed library?
installed=yes

# Directory that this library needs to be installed in:
libdir='$GLOBUS_LOCATION/libexec/openldap/vendorcc32dbgpthr'

EOF


cat > $GLOBUS_LOCATION/libexec/openldap/vendorcc32dbgpthr/libback_ldif.la << EOF


# libback_ldif.la - a libtool library file
# Generated by ltmain.sh - GNU libtool 1.3.5 (1.385.2.206 2000/05/27 11:12:27)
#
# Please DO NOT delete this file!
# It is necessary for linking the library.

# The name that we can dlopen(3).
B
dlname='libback_ldif.so.0'

# Names of this library.
library_names=''

# The name of the static archive.
old_library=''

# Libraries that this one depends upon.
dependency_libs=' -L$GLOBUS_LOCATION/lib -lglobus_gss_assist_vendorcc32dbgpthr -lldap_vendorcc32dbgpthr -llber_vendorcc32dbgpthr -lglobus_gssapi_gsi_vendorcc32dbgpthr -lsasl_vendorcc32dbgpthr -lglobus_ssl_utils_vendorcc32dbgpthr -lltdl_vendorcc32dbgpthr -lssl_vendorcc32dbgpthr -lcrypto_vendorcc32dbgpthr'

# Version information for libback_ldif.
current=0
age=0
revision=0

# Is this an already installed library?
installed=yes

# Directory that this library needs to be installed in:
libdir='$GLOBUS_LOCATION/libexec/openldap/vendorcc32dbgpthr'
EOF

cd ${BUILD_DIR}/globus_openldap-2.0.22/openldap-2.0.22/servers/slapd

cc *.o -brtl -bexpall libbackends.a -L/$GLOBUS_LOCATION/lib -L ../../libraries -lavl -lldif -lldbm -llutil_vendorcc32dbgpthr -lldap_r_vendorcc32dbgpthr -llber_vendorcc32dbgpthr -lsasl_vendorcc32dbgpthr -lssl_vendorcc32dbgpthr -lcrypto_vendorcc32dbgpthr -ls -lltdl_vendorcc32dbgpthr -lpthread -o slapd $GLOBUS_LOCATION/libexec/openldap/vendorcc32dbgpthr/libback_ldif.so $GLOBUS_LOCATION/libexec/openldap/vendorcc32dbgpthr/libback_giis.so

cp slapd $GLOBUS_LOCATION/libexec

